spring:
  active: prod
  webflux:
    base-path: /api

server:
  port: ${SERVER_PORT:9090}

grpc:
  port: ${GRPC_PORT:19090}

accessible:
  endpoints:
    "[POST-/api/user/create]": ${CREATE_USER:true}
    "[POST-/api/user/login]": ${LOGIN_USER:true}
    "[POST-/api/user/logout]": ${LOGOUT_USER:true}
    "[GET-/actuator/info]": ${ACTUATOR_INFO:true}
    "[GET-/actuator/prometheus]": ${GET_METRICS:true}
    "[GET-/actuator/mappings]": ${GET_MAPPINGS:true}
    "[GET-/api/v2/api-docs]": ${GET_SWAGGER_JSON:true}
    "[GET-/api/swagger-ui/]": ${GET_SWAGGER_UI:true}
    "[GET-/api/swagger-resources]": ${GET_SWAGGER_RESOURCES:true}
  endpointsRegex:
    "[GET-/api/swagger-resources/.*]": ${GET_SWAGGER_RESOURCES:true}
    "[GET-/api/swagger-ui/.*]": ${GET_SWAGGER_UI_RESOURCES:true}
    "[GET-/actuator/health/.*]": ${ACTUATOR_HEALTH_CUSTOM:true}
    "[GET-/api/user/details/.*]": ${FETCH_USER:true}

management:
  server.port: ${SERVER_MGT_PORT:9091}
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure.include: health, mappings, metrics, prometheus, configprops
      path-mapping:
        configprops: config

auth:
  tokenDuration: ${TOKEN_DURATION:3650D}
  secret: ${SECRET:19CA249C582715657BDCAB1FB31E69F854443A4FE3CBAFFD215E3F3676}

database:
  username: ${DB_USER:user_data}
  password: ${DB_PWD:user_data}
  database: ${NEW_DB_NAME:user_data}
  hostname: ${DB_HOST:user_data}
  scheme: ${DB_SCHEME:mongodb+srv}

vault:
  token: ${VAULT_ACCESS_TOKEN:root}
  host: ${VAULT_HOST:local.vault}
  port: ${VAULT_PORT:8200}
  httpScheme: "http"
  appRole: "user_service"

cache:
  host: ${CACHE_HOST:localhost}
  port: ${CACHE_PORT:6379}
