# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/gw-annotations" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/gw-common" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/gw-functionalTest" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/gw-grpc-common" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/gw-grpc-schema" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/gw-security" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "gw-test-common"
    directory: "/user-client" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "gw-ui"
    directory: "/user-client" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "gw-user"
    directory: "/user-client" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "gw-user-client"
    directory: "/user-client" # Location of package manifests
    schedule:
      interval: "daily"
