version: '3.7'
services:
  gw-user-app:
    container_name: local.user-app
    build:
      context: gw-user
    depends_on:
      - postgres
      - gw-security
    ports:
      - "19090:19090"
      - "9090:9090"
    environment:
      - "DB_NAME=testUserDB"
    networks:
      - overlay

  gw-api-gateway:
    container_name: local.api-gateway
    depends_on:
      - gw-user-app
      - gw-security
    build:
      context: gw-api-gateway
    environment:
      - "VAULT_ADDRESS=local.vault:8200"
      - "VAULT_TOKEN=root"
    command: [nginx-debug, '-g', 'daemon off;']
    ports:
      - "80:80"
      - "443:443"
    networks:
      - overlay

  gw-ui:
    container_name: local.gw-ui
    build:
      context: gw-ui
    depends_on:
      - gw-api-gateway
    ports:
      - "7070:8080"
      - "7080:8090"
    networks:
      - overlay

  postgres:
    image: postgres:14.1
    container_name: local.postgres
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_USER=user"
      - "POSTGRES_PASSWORD=password"
      - "POSTGRES_DB=testUserDB"
    networks:
      - overlay

  gw-security:
    container_name: local.vault
    build:
      context: gw-security
    environment:
      - "VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200"
    ports:
      - "8200:8200"
    networks:
      - overlay

networks:
  overlay: