version: '3.7'
services:
  user-app:
    container_name: local.user-app
    build:
      context: user
    depends_on:
      - postgres
      - vault
    ports:
      - "19090:19090"
      - "9090:9090"
    environment:
      - "DB_NAME=testUserDB"
      - "DEPLOY_ENV=dev" #Only needed for Dev
    networks:
      - overlay

  api-gateway:
    container_name: local.api-gateway
    depends_on:
      - user-app
    build:
      context: api-gateway
    ports:
      - "8080:8080"
      - "443:443"
    networks:
      - overlay

  postgres:
    image: postgres:14.1
    container_name: local.postgres
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_USER=user"
      - "POSTGRES_PASSWORD=password"
      - "POSTGRES_DB=testUserDB"
    networks:
      - overlay

  vault:
    container_name: local.vault
    build:
      context: vault
    environment:
      - "VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200"
    ports:
      - "8200:8200"
    networks:
      - overlay

networks:
  overlay: