spring:
  active: prod
  webflux:
    base-path: /api

server:
  port: ${SERVER_PORT:6060}

management:
  server.port: ${SERVER_MGT_PORT:6061}
  endpoints:
    web:
      exposure.include: mappings, metrics, prometheus, configprops
