spring:
  active: prod
  webflux:
    base-path: /api

server:
  port: ${SERVER_PORT:6060}

management:
  server.port: ${SERVER_MGT_PORT:6061}
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure.include: health, mappings, metrics, prometheus, configprops
      path-mapping:
        health: healthcheck
        configprops: config
