// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserService.proto

package com.gw.user.grpc;

public interface FetchUserDetailsByNameGrpcRequestDTOOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.gw.user.grpc.FetchUserDetailsByNameGrpcRequestDTO)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
