// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: userservice.proto

package com.gw.user.grpc;

public interface UserAuthResponseDTOOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.gw.user.grpc.UserAuthResponseDTO)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.gw.user.grpc.UserAuthDetailsDTO authDetails = 1;</code>
   * @return Whether the authDetails field is set.
   */
  boolean hasAuthDetails();
  /**
   * <code>.com.gw.user.grpc.UserAuthDetailsDTO authDetails = 1;</code>
   * @return The authDetails.
   */
  com.gw.user.grpc.UserAuthDetailsDTO getAuthDetails();
  /**
   * <code>.com.gw.user.grpc.UserAuthDetailsDTO authDetails = 1;</code>
   */
  com.gw.user.grpc.UserAuthDetailsDTOOrBuilder getAuthDetailsOrBuilder();

  /**
   * <code>.com.gw.common.grpc.GenesisError error = 2;</code>
   * @return Whether the error field is set.
   */
  boolean hasError();
  /**
   * <code>.com.gw.common.grpc.GenesisError error = 2;</code>
   * @return The error.
   */
  com.gw.common.grpc.GenesisError getError();
  /**
   * <code>.com.gw.common.grpc.GenesisError error = 2;</code>
   */
  com.gw.common.grpc.GenesisErrorOrBuilder getErrorOrBuilder();

  public com.gw.user.grpc.UserAuthResponseDTO.EitherCase getEitherCase();
}
