// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserService.proto

package com.gw.user.grpc;

public interface ExternalUserCreateGrpcRequestDTOOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.gw.user.grpc.ExternalUserCreateGrpcRequestDTO)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string email = 1;</code>
   * @return The email.
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 1;</code>
   * @return The bytes for email.
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>string locale = 2;</code>
   * @return The locale.
   */
  java.lang.String getLocale();
  /**
   * <code>string locale = 2;</code>
   * @return The bytes for locale.
   */
  com.google.protobuf.ByteString
      getLocaleBytes();

  /**
   * <code>string pictureUrl = 3;</code>
   * @return The pictureUrl.
   */
  java.lang.String getPictureUrl();
  /**
   * <code>string pictureUrl = 3;</code>
   * @return The bytes for pictureUrl.
   */
  com.google.protobuf.ByteString
      getPictureUrlBytes();

  /**
   * <code>string firstName = 4;</code>
   * @return The firstName.
   */
  java.lang.String getFirstName();
  /**
   * <code>string firstName = 4;</code>
   * @return The bytes for firstName.
   */
  com.google.protobuf.ByteString
      getFirstNameBytes();

  /**
   * <code>string lastName = 5;</code>
   * @return The lastName.
   */
  java.lang.String getLastName();
  /**
   * <code>string lastName = 5;</code>
   * @return The bytes for lastName.
   */
  com.google.protobuf.ByteString
      getLastNameBytes();

  /**
   * <code>string tokenValue = 6;</code>
   * @return The tokenValue.
   */
  java.lang.String getTokenValue();
  /**
   * <code>string tokenValue = 6;</code>
   * @return The bytes for tokenValue.
   */
  com.google.protobuf.ByteString
      getTokenValueBytes();

  /**
   * <code>string tokenType = 7;</code>
   * @return The tokenType.
   */
  java.lang.String getTokenType();
  /**
   * <code>string tokenType = 7;</code>
   * @return The bytes for tokenType.
   */
  com.google.protobuf.ByteString
      getTokenTypeBytes();

  /**
   * <code>int64 tokenExpiryTime = 8;</code>
   * @return The tokenExpiryTime.
   */
  long getTokenExpiryTime();

  /**
   * <code>string externalSystem = 10;</code>
   * @return The externalSystem.
   */
  java.lang.String getExternalSystem();
  /**
   * <code>string externalSystem = 10;</code>
   * @return The bytes for externalSystem.
   */
  com.google.protobuf.ByteString
      getExternalSystemBytes();

  /**
   * <code>string dateOfBirth = 11;</code>
   * @return The dateOfBirth.
   */
  java.lang.String getDateOfBirth();
  /**
   * <code>string dateOfBirth = 11;</code>
   * @return The bytes for dateOfBirth.
   */
  com.google.protobuf.ByteString
      getDateOfBirthBytes();

  /**
   * <code>.com.gw.user.grpc.Gender gender = 12;</code>
   * @return The enum numeric value on the wire for gender.
   */
  int getGenderValue();
  /**
   * <code>.com.gw.user.grpc.Gender gender = 12;</code>
   * @return The gender.
   */
  com.gw.user.grpc.Gender getGender();

  /**
   * <code>string homeCountry = 13;</code>
   * @return The homeCountry.
   */
  java.lang.String getHomeCountry();
  /**
   * <code>string homeCountry = 13;</code>
   * @return The bytes for homeCountry.
   */
  com.google.protobuf.ByteString
      getHomeCountryBytes();
}
