// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserService.proto

package com.gw.user.grpc;

public interface ExternalUserCreateGrpcRequestDTOOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.gw.user.grpc.ExternalUserCreateGrpcRequestDTO)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string email = 1;</code>
   * @return The email.
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 1;</code>
   * @return The bytes for email.
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>string firstName = 2;</code>
   * @return The firstName.
   */
  java.lang.String getFirstName();
  /**
   * <code>string firstName = 2;</code>
   * @return The bytes for firstName.
   */
  com.google.protobuf.ByteString
      getFirstNameBytes();

  /**
   * <code>string lastName = 3;</code>
   * @return The lastName.
   */
  java.lang.String getLastName();
  /**
   * <code>string lastName = 3;</code>
   * @return The bytes for lastName.
   */
  com.google.protobuf.ByteString
      getLastNameBytes();

  /**
   * <code>string tokenValue = 4;</code>
   * @return The tokenValue.
   */
  java.lang.String getTokenValue();
  /**
   * <code>string tokenValue = 4;</code>
   * @return The bytes for tokenValue.
   */
  com.google.protobuf.ByteString
      getTokenValueBytes();

  /**
   * <code>string tokenType = 5;</code>
   * @return The tokenType.
   */
  java.lang.String getTokenType();
  /**
   * <code>string tokenType = 5;</code>
   * @return The bytes for tokenType.
   */
  com.google.protobuf.ByteString
      getTokenTypeBytes();

  /**
   * <code>int64 tokenExpiryTime = 6;</code>
   * @return The tokenExpiryTime.
   */
  long getTokenExpiryTime();

  /**
   * <code>string externalSystem = 7;</code>
   * @return The externalSystem.
   */
  java.lang.String getExternalSystem();
  /**
   * <code>string externalSystem = 7;</code>
   * @return The bytes for externalSystem.
   */
  com.google.protobuf.ByteString
      getExternalSystemBytes();
}
