// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: userservice.proto

package com.gw.user.grpc;

public interface ExternalUserCreateGrpcResponseDTOOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.gw.user.grpc.ExternalUserCreateGrpcResponseDTO)
    com.google.protobuf.MessageOrBuilder {
}
