// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserService.proto

package com.gw.user.grpc;

/**
 * Protobuf type {@code com.gw.user.grpc.ExternalUserCreateGrpcRequestDTO}
 */
public final class ExternalUserCreateGrpcRequestDTO extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.gw.user.grpc.ExternalUserCreateGrpcRequestDTO)
    ExternalUserCreateGrpcRequestDTOOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ExternalUserCreateGrpcRequestDTO.newBuilder() to construct.
  private ExternalUserCreateGrpcRequestDTO(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ExternalUserCreateGrpcRequestDTO() {
    email_ = "";
    firstName_ = "";
    lastName_ = "";
    tokenValue_ = "";
    tokenType_ = "";
    externalSystem_ = "";
    dateOfBirth_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ExternalUserCreateGrpcRequestDTO();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.gw.user.grpc.UserManagementGrpc.internal_static_com_gw_user_grpc_ExternalUserCreateGrpcRequestDTO_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.gw.user.grpc.UserManagementGrpc.internal_static_com_gw_user_grpc_ExternalUserCreateGrpcRequestDTO_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.gw.user.grpc.ExternalUserCreateGrpcRequestDTO.class, com.gw.user.grpc.ExternalUserCreateGrpcRequestDTO.Builder.class);
  }

  public static final int EMAIL_FIELD_NUMBER = 1;
  private volatile java.lang.Object email_;
  /**
   * <code>string email = 1;</code>
   * @return The email.
   */
  @java.lang.Override
  public java.lang.String getEmail() {
    java.lang.Object ref = email_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      email_ = s;
      return s;
    }
  }
  /**
   * <code>string email = 1;</code>
   * @return The bytes for email.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEmailBytes() {
    java.lang.Object ref = email_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      email_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FIRSTNAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object firstName_;
  /**
   * <code>string firstName = 2;</code>
   * @return The firstName.
   */
  @java.lang.Override
  public java.lang.String getFirstName() {
    java.lang.Object ref = firstName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      firstName_ = s;
      return s;
    }
  }
  /**
   * <code>string firstName = 2;</code>
   * @return The bytes for firstName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFirstNameBytes() {
    java.lang.Object ref = firstName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      firstName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LASTNAME_FIELD_NUMBER = 3;
  private volatile java.lang.Object lastName_;
  /**
   * <code>string lastName = 3;</code>
   * @return The lastName.
   */
  @java.lang.Override
  public java.lang.String getLastName() {
    java.lang.Object ref = lastName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      lastName_ = s;
      return s;
    }
  }
  /**
   * <code>string lastName = 3;</code>
   * @return The bytes for lastName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLastNameBytes() {
    java.lang.Object ref = lastName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      lastName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TOKENVALUE_FIELD_NUMBER = 4;
  private volatile java.lang.Object tokenValue_;
  /**
   * <code>string tokenValue = 4;</code>
   * @return The tokenValue.
   */
  @java.lang.Override
  public java.lang.String getTokenValue() {
    java.lang.Object ref = tokenValue_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      tokenValue_ = s;
      return s;
    }
  }
  /**
   * <code>string tokenValue = 4;</code>
   * @return The bytes for tokenValue.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTokenValueBytes() {
    java.lang.Object ref = tokenValue_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      tokenValue_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TOKENTYPE_FIELD_NUMBER = 5;
  private volatile java.lang.Object tokenType_;
  /**
   * <code>string tokenType = 5;</code>
   * @return The tokenType.
   */
  @java.lang.Override
  public java.lang.String getTokenType() {
    java.lang.Object ref = tokenType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      tokenType_ = s;
      return s;
    }
  }
  /**
   * <code>string tokenType = 5;</code>
   * @return The bytes for tokenType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTokenTypeBytes() {
    java.lang.Object ref = tokenType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      tokenType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TOKENEXPIRYTIME_FIELD_NUMBER = 6;
  private long tokenExpiryTime_;
  /**
   * <code>int64 tokenExpiryTime = 6;</code>
   * @return The tokenExpiryTime.
   */
  @java.lang.Override
  public long getTokenExpiryTime() {
    return tokenExpiryTime_;
  }

  public static final int EXTERNALSYSTEM_FIELD_NUMBER = 7;
  private volatile java.lang.Object externalSystem_;
  /**
   * <code>string externalSystem = 7;</code>
   * @return The externalSystem.
   */
  @java.lang.Override
  public java.lang.String getExternalSystem() {
    java.lang.Object ref = externalSystem_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      externalSystem_ = s;
      return s;
    }
  }
  /**
   * <code>string externalSystem = 7;</code>
   * @return The bytes for externalSystem.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getExternalSystemBytes() {
    java.lang.Object ref = externalSystem_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      externalSystem_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DATEOFBIRTH_FIELD_NUMBER = 8;
  private volatile java.lang.Object dateOfBirth_;
  /**
   * <code>string dateOfBirth = 8;</code>
   * @return The dateOfBirth.
   */
  @java.lang.Override
  public java.lang.String getDateOfBirth() {
    java.lang.Object ref = dateOfBirth_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      dateOfBirth_ = s;
      return s;
    }
  }
  /**
   * <code>string dateOfBirth = 8;</code>
   * @return The bytes for dateOfBirth.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDateOfBirthBytes() {
    java.lang.Object ref = dateOfBirth_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      dateOfBirth_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(email_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, email_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(firstName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, firstName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(lastName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, lastName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tokenValue_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, tokenValue_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tokenType_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, tokenType_);
    }
    if (tokenExpiryTime_ != 0L) {
      output.writeInt64(6, tokenExpiryTime_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(externalSystem_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, externalSystem_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(dateOfBirth_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, dateOfBirth_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(email_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, email_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(firstName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, firstName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(lastName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, lastName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tokenValue_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, tokenValue_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tokenType_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, tokenType_);
    }
    if (tokenExpiryTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, tokenExpiryTime_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(externalSystem_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, externalSystem_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(dateOfBirth_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, dateOfBirth_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.gw.user.grpc.ExternalUserCreateGrpcRequestDTO)) {
      return super.equals(obj);
    }
    com.gw.user.grpc.ExternalUserCreateGrpcRequestDTO other = (com.gw.user.grpc.ExternalUserCreateGrpcRequestDTO) obj;

    if (!getEmail()
        .equals(other.getEmail())) return false;
    if (!getFirstName()
        .equals(other.getFirstName())) return false;
    if (!getLastName()
        .equals(other.getLastName())) return false;
    if (!getTokenValue()
        .equals(other.getTokenValue())) return false;
    if (!getTokenType()
        .equals(other.getTokenType())) return false;
    if (getTokenExpiryTime()
        != other.getTokenExpiryTime()) return false;
    if (!getExternalSystem()
        .equals(other.getExternalSystem())) return false;
    if (!getDateOfBirth()
        .equals(other.getDateOfBirth())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + EMAIL_FIELD_NUMBER;
    hash = (53 * hash) + getEmail().hashCode();
    hash = (37 * hash) + FIRSTNAME_FIELD_NUMBER;
    hash = (53 * hash) + getFirstName().hashCode();
    hash = (37 * hash) + LASTNAME_FIELD_NUMBER;
    hash = (53 * hash) + getLastName().hashCode();
    hash = (37 * hash) + TOKENVALUE_FIELD_NUMBER;
    hash = (53 * hash) + getTokenValue().hashCode();
    hash = (37 * hash) + TOKENTYPE_FIELD_NUMBER;
    hash = (53 * hash) + getTokenType().hashCode();
    hash = (37 * hash) + TOKENEXPIRYTIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTokenExpiryTime());
    hash = (37 * hash) + EXTERNALSYSTEM_FIELD_NUMBER;
    hash = (53 * hash) + getExternalSystem().hashCode();
    hash = (37 * hash) + DATEOFBIRTH_FIELD_NUMBER;
    hash = (53 * hash) + getDateOfBirth().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.gw.user.grpc.ExternalUserCreateGrpcRequestDTO parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gw.user.grpc.ExternalUserCreateGrpcRequestDTO parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gw.user.grpc.ExternalUserCreateGrpcRequestDTO parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gw.user.grpc.ExternalUserCreateGrpcRequestDTO parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gw.user.grpc.ExternalUserCreateGrpcRequestDTO parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gw.user.grpc.ExternalUserCreateGrpcRequestDTO parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gw.user.grpc.ExternalUserCreateGrpcRequestDTO parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.gw.user.grpc.ExternalUserCreateGrpcRequestDTO parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.gw.user.grpc.ExternalUserCreateGrpcRequestDTO parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.gw.user.grpc.ExternalUserCreateGrpcRequestDTO parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.gw.user.grpc.ExternalUserCreateGrpcRequestDTO parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.gw.user.grpc.ExternalUserCreateGrpcRequestDTO parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.gw.user.grpc.ExternalUserCreateGrpcRequestDTO prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.gw.user.grpc.ExternalUserCreateGrpcRequestDTO}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.gw.user.grpc.ExternalUserCreateGrpcRequestDTO)
      com.gw.user.grpc.ExternalUserCreateGrpcRequestDTOOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gw.user.grpc.UserManagementGrpc.internal_static_com_gw_user_grpc_ExternalUserCreateGrpcRequestDTO_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gw.user.grpc.UserManagementGrpc.internal_static_com_gw_user_grpc_ExternalUserCreateGrpcRequestDTO_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gw.user.grpc.ExternalUserCreateGrpcRequestDTO.class, com.gw.user.grpc.ExternalUserCreateGrpcRequestDTO.Builder.class);
    }

    // Construct using com.gw.user.grpc.ExternalUserCreateGrpcRequestDTO.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      email_ = "";

      firstName_ = "";

      lastName_ = "";

      tokenValue_ = "";

      tokenType_ = "";

      tokenExpiryTime_ = 0L;

      externalSystem_ = "";

      dateOfBirth_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.gw.user.grpc.UserManagementGrpc.internal_static_com_gw_user_grpc_ExternalUserCreateGrpcRequestDTO_descriptor;
    }

    @java.lang.Override
    public com.gw.user.grpc.ExternalUserCreateGrpcRequestDTO getDefaultInstanceForType() {
      return com.gw.user.grpc.ExternalUserCreateGrpcRequestDTO.getDefaultInstance();
    }

    @java.lang.Override
    public com.gw.user.grpc.ExternalUserCreateGrpcRequestDTO build() {
      com.gw.user.grpc.ExternalUserCreateGrpcRequestDTO result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.gw.user.grpc.ExternalUserCreateGrpcRequestDTO buildPartial() {
      com.gw.user.grpc.ExternalUserCreateGrpcRequestDTO result = new com.gw.user.grpc.ExternalUserCreateGrpcRequestDTO(this);
      result.email_ = email_;
      result.firstName_ = firstName_;
      result.lastName_ = lastName_;
      result.tokenValue_ = tokenValue_;
      result.tokenType_ = tokenType_;
      result.tokenExpiryTime_ = tokenExpiryTime_;
      result.externalSystem_ = externalSystem_;
      result.dateOfBirth_ = dateOfBirth_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.gw.user.grpc.ExternalUserCreateGrpcRequestDTO) {
        return mergeFrom((com.gw.user.grpc.ExternalUserCreateGrpcRequestDTO)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.gw.user.grpc.ExternalUserCreateGrpcRequestDTO other) {
      if (other == com.gw.user.grpc.ExternalUserCreateGrpcRequestDTO.getDefaultInstance()) return this;
      if (!other.getEmail().isEmpty()) {
        email_ = other.email_;
        onChanged();
      }
      if (!other.getFirstName().isEmpty()) {
        firstName_ = other.firstName_;
        onChanged();
      }
      if (!other.getLastName().isEmpty()) {
        lastName_ = other.lastName_;
        onChanged();
      }
      if (!other.getTokenValue().isEmpty()) {
        tokenValue_ = other.tokenValue_;
        onChanged();
      }
      if (!other.getTokenType().isEmpty()) {
        tokenType_ = other.tokenType_;
        onChanged();
      }
      if (other.getTokenExpiryTime() != 0L) {
        setTokenExpiryTime(other.getTokenExpiryTime());
      }
      if (!other.getExternalSystem().isEmpty()) {
        externalSystem_ = other.externalSystem_;
        onChanged();
      }
      if (!other.getDateOfBirth().isEmpty()) {
        dateOfBirth_ = other.dateOfBirth_;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              email_ = input.readStringRequireUtf8();

              break;
            } // case 10
            case 18: {
              firstName_ = input.readStringRequireUtf8();

              break;
            } // case 18
            case 26: {
              lastName_ = input.readStringRequireUtf8();

              break;
            } // case 26
            case 34: {
              tokenValue_ = input.readStringRequireUtf8();

              break;
            } // case 34
            case 42: {
              tokenType_ = input.readStringRequireUtf8();

              break;
            } // case 42
            case 48: {
              tokenExpiryTime_ = input.readInt64();

              break;
            } // case 48
            case 58: {
              externalSystem_ = input.readStringRequireUtf8();

              break;
            } // case 58
            case 66: {
              dateOfBirth_ = input.readStringRequireUtf8();

              break;
            } // case 66
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    private java.lang.Object email_ = "";
    /**
     * <code>string email = 1;</code>
     * @return The email.
     */
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        email_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string email = 1;</code>
     * @return The bytes for email.
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string email = 1;</code>
     * @param value The email to set.
     * @return This builder for chaining.
     */
    public Builder setEmail(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      email_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string email = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearEmail() {
      
      email_ = getDefaultInstance().getEmail();
      onChanged();
      return this;
    }
    /**
     * <code>string email = 1;</code>
     * @param value The bytes for email to set.
     * @return This builder for chaining.
     */
    public Builder setEmailBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      email_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object firstName_ = "";
    /**
     * <code>string firstName = 2;</code>
     * @return The firstName.
     */
    public java.lang.String getFirstName() {
      java.lang.Object ref = firstName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        firstName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string firstName = 2;</code>
     * @return The bytes for firstName.
     */
    public com.google.protobuf.ByteString
        getFirstNameBytes() {
      java.lang.Object ref = firstName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        firstName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string firstName = 2;</code>
     * @param value The firstName to set.
     * @return This builder for chaining.
     */
    public Builder setFirstName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      firstName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string firstName = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearFirstName() {
      
      firstName_ = getDefaultInstance().getFirstName();
      onChanged();
      return this;
    }
    /**
     * <code>string firstName = 2;</code>
     * @param value The bytes for firstName to set.
     * @return This builder for chaining.
     */
    public Builder setFirstNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      firstName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object lastName_ = "";
    /**
     * <code>string lastName = 3;</code>
     * @return The lastName.
     */
    public java.lang.String getLastName() {
      java.lang.Object ref = lastName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lastName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string lastName = 3;</code>
     * @return The bytes for lastName.
     */
    public com.google.protobuf.ByteString
        getLastNameBytes() {
      java.lang.Object ref = lastName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lastName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string lastName = 3;</code>
     * @param value The lastName to set.
     * @return This builder for chaining.
     */
    public Builder setLastName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      lastName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string lastName = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearLastName() {
      
      lastName_ = getDefaultInstance().getLastName();
      onChanged();
      return this;
    }
    /**
     * <code>string lastName = 3;</code>
     * @param value The bytes for lastName to set.
     * @return This builder for chaining.
     */
    public Builder setLastNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      lastName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object tokenValue_ = "";
    /**
     * <code>string tokenValue = 4;</code>
     * @return The tokenValue.
     */
    public java.lang.String getTokenValue() {
      java.lang.Object ref = tokenValue_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tokenValue_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string tokenValue = 4;</code>
     * @return The bytes for tokenValue.
     */
    public com.google.protobuf.ByteString
        getTokenValueBytes() {
      java.lang.Object ref = tokenValue_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tokenValue_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string tokenValue = 4;</code>
     * @param value The tokenValue to set.
     * @return This builder for chaining.
     */
    public Builder setTokenValue(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      tokenValue_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string tokenValue = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearTokenValue() {
      
      tokenValue_ = getDefaultInstance().getTokenValue();
      onChanged();
      return this;
    }
    /**
     * <code>string tokenValue = 4;</code>
     * @param value The bytes for tokenValue to set.
     * @return This builder for chaining.
     */
    public Builder setTokenValueBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      tokenValue_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object tokenType_ = "";
    /**
     * <code>string tokenType = 5;</code>
     * @return The tokenType.
     */
    public java.lang.String getTokenType() {
      java.lang.Object ref = tokenType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tokenType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string tokenType = 5;</code>
     * @return The bytes for tokenType.
     */
    public com.google.protobuf.ByteString
        getTokenTypeBytes() {
      java.lang.Object ref = tokenType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tokenType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string tokenType = 5;</code>
     * @param value The tokenType to set.
     * @return This builder for chaining.
     */
    public Builder setTokenType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      tokenType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string tokenType = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearTokenType() {
      
      tokenType_ = getDefaultInstance().getTokenType();
      onChanged();
      return this;
    }
    /**
     * <code>string tokenType = 5;</code>
     * @param value The bytes for tokenType to set.
     * @return This builder for chaining.
     */
    public Builder setTokenTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      tokenType_ = value;
      onChanged();
      return this;
    }

    private long tokenExpiryTime_ ;
    /**
     * <code>int64 tokenExpiryTime = 6;</code>
     * @return The tokenExpiryTime.
     */
    @java.lang.Override
    public long getTokenExpiryTime() {
      return tokenExpiryTime_;
    }
    /**
     * <code>int64 tokenExpiryTime = 6;</code>
     * @param value The tokenExpiryTime to set.
     * @return This builder for chaining.
     */
    public Builder setTokenExpiryTime(long value) {
      
      tokenExpiryTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 tokenExpiryTime = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearTokenExpiryTime() {
      
      tokenExpiryTime_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object externalSystem_ = "";
    /**
     * <code>string externalSystem = 7;</code>
     * @return The externalSystem.
     */
    public java.lang.String getExternalSystem() {
      java.lang.Object ref = externalSystem_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        externalSystem_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string externalSystem = 7;</code>
     * @return The bytes for externalSystem.
     */
    public com.google.protobuf.ByteString
        getExternalSystemBytes() {
      java.lang.Object ref = externalSystem_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        externalSystem_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string externalSystem = 7;</code>
     * @param value The externalSystem to set.
     * @return This builder for chaining.
     */
    public Builder setExternalSystem(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      externalSystem_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string externalSystem = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearExternalSystem() {
      
      externalSystem_ = getDefaultInstance().getExternalSystem();
      onChanged();
      return this;
    }
    /**
     * <code>string externalSystem = 7;</code>
     * @param value The bytes for externalSystem to set.
     * @return This builder for chaining.
     */
    public Builder setExternalSystemBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      externalSystem_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object dateOfBirth_ = "";
    /**
     * <code>string dateOfBirth = 8;</code>
     * @return The dateOfBirth.
     */
    public java.lang.String getDateOfBirth() {
      java.lang.Object ref = dateOfBirth_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dateOfBirth_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string dateOfBirth = 8;</code>
     * @return The bytes for dateOfBirth.
     */
    public com.google.protobuf.ByteString
        getDateOfBirthBytes() {
      java.lang.Object ref = dateOfBirth_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dateOfBirth_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string dateOfBirth = 8;</code>
     * @param value The dateOfBirth to set.
     * @return This builder for chaining.
     */
    public Builder setDateOfBirth(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      dateOfBirth_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string dateOfBirth = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearDateOfBirth() {
      
      dateOfBirth_ = getDefaultInstance().getDateOfBirth();
      onChanged();
      return this;
    }
    /**
     * <code>string dateOfBirth = 8;</code>
     * @param value The bytes for dateOfBirth to set.
     * @return This builder for chaining.
     */
    public Builder setDateOfBirthBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      dateOfBirth_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.gw.user.grpc.ExternalUserCreateGrpcRequestDTO)
  }

  // @@protoc_insertion_point(class_scope:com.gw.user.grpc.ExternalUserCreateGrpcRequestDTO)
  private static final com.gw.user.grpc.ExternalUserCreateGrpcRequestDTO DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.gw.user.grpc.ExternalUserCreateGrpcRequestDTO();
  }

  public static com.gw.user.grpc.ExternalUserCreateGrpcRequestDTO getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ExternalUserCreateGrpcRequestDTO>
      PARSER = new com.google.protobuf.AbstractParser<ExternalUserCreateGrpcRequestDTO>() {
    @java.lang.Override
    public ExternalUserCreateGrpcRequestDTO parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ExternalUserCreateGrpcRequestDTO> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ExternalUserCreateGrpcRequestDTO> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.gw.user.grpc.ExternalUserCreateGrpcRequestDTO getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

