// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserService.proto

package com.gw.user.grpc;

public interface FetchUserDetailsByUserNameGrpcRequestDTOOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.gw.user.grpc.FetchUserDetailsByUserNameGrpcRequestDTO)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string userName = 1;</code>
   * @return The userName.
   */
  java.lang.String getUserName();
  /**
   * <code>string userName = 1;</code>
   * @return The bytes for userName.
   */
  com.google.protobuf.ByteString
      getUserNameBytes();
}
