// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: userservice.proto

package com.gw.user.grpc;

public interface UserCreateOrFindGrpcResponseDTOOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.gw.user.grpc.UserCreateOrFindGrpcResponseDTO)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.gw.user.grpc.OauthUser user = 1;</code>
   * @return Whether the user field is set.
   */
  boolean hasUser();
  /**
   * <code>.com.gw.user.grpc.OauthUser user = 1;</code>
   * @return The user.
   */
  com.gw.user.grpc.OauthUser getUser();
  /**
   * <code>.com.gw.user.grpc.OauthUser user = 1;</code>
   */
  com.gw.user.grpc.OauthUserOrBuilder getUserOrBuilder();

  /**
   * <code>.com.gw.common.grpc.Error error = 2;</code>
   * @return Whether the error field is set.
   */
  boolean hasError();
  /**
   * <code>.com.gw.common.grpc.Error error = 2;</code>
   * @return The error.
   */
  com.gw.common.grpc.Error getError();
  /**
   * <code>.com.gw.common.grpc.Error error = 2;</code>
   */
  com.gw.common.grpc.ErrorOrBuilder getErrorOrBuilder();

  public com.gw.user.grpc.UserCreateOrFindGrpcResponseDTO.EitherCase getEitherCase();
}
