// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: userservice.proto

package com.gw.user.grpc;

public interface UserCreateOrFindGrpcRequestDTOOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.gw.user.grpc.UserCreateOrFindGrpcRequestDTO)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string userName = 1;</code>
   * @return The userName.
   */
  java.lang.String getUserName();
  /**
   * <code>string userName = 1;</code>
   * @return The bytes for userName.
   */
  com.google.protobuf.ByteString
      getUserNameBytes();

  /**
   * <code>.com.gw.user.grpc.ExternalSystem extsource = 2;</code>
   * @return The enum numeric value on the wire for extsource.
   */
  int getExtsourceValue();
  /**
   * <code>.com.gw.user.grpc.ExternalSystem extsource = 2;</code>
   * @return The extsource.
   */
  com.gw.user.grpc.ExternalSystem getExtsource();
}
