// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserService.proto

package com.gw.user.grpc;

/**
 * Protobuf type {@code com.gw.user.grpc.UserCreateGrpcRequestDTO}
 */
public final class UserCreateGrpcRequestDTO extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.gw.user.grpc.UserCreateGrpcRequestDTO)
    UserCreateGrpcRequestDTOOrBuilder {
private static final long serialVersionUID = 0L;
  // Use UserCreateGrpcRequestDTO.newBuilder() to construct.
  private UserCreateGrpcRequestDTO(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UserCreateGrpcRequestDTO() {
    userName_ = "";
    password_ = "";
    salt_ = "";
    firstName_ = "";
    lastName_ = "";
    dateOfBirth_ = "";
    gender_ = 0;
    homeCountry_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new UserCreateGrpcRequestDTO();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.gw.user.grpc.UserManagementGrpc.internal_static_com_gw_user_grpc_UserCreateGrpcRequestDTO_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.gw.user.grpc.UserManagementGrpc.internal_static_com_gw_user_grpc_UserCreateGrpcRequestDTO_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.gw.user.grpc.UserCreateGrpcRequestDTO.class, com.gw.user.grpc.UserCreateGrpcRequestDTO.Builder.class);
  }

  public static final int USERNAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object userName_;
  /**
   * <code>string userName = 1;</code>
   * @return The userName.
   */
  @java.lang.Override
  public java.lang.String getUserName() {
    java.lang.Object ref = userName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      userName_ = s;
      return s;
    }
  }
  /**
   * <code>string userName = 1;</code>
   * @return The bytes for userName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUserNameBytes() {
    java.lang.Object ref = userName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      userName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PASSWORD_FIELD_NUMBER = 2;
  private volatile java.lang.Object password_;
  /**
   * <code>string password = 2;</code>
   * @return The password.
   */
  @java.lang.Override
  public java.lang.String getPassword() {
    java.lang.Object ref = password_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      password_ = s;
      return s;
    }
  }
  /**
   * <code>string password = 2;</code>
   * @return The bytes for password.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPasswordBytes() {
    java.lang.Object ref = password_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      password_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SALT_FIELD_NUMBER = 3;
  private volatile java.lang.Object salt_;
  /**
   * <code>string salt = 3;</code>
   * @return The salt.
   */
  @java.lang.Override
  public java.lang.String getSalt() {
    java.lang.Object ref = salt_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      salt_ = s;
      return s;
    }
  }
  /**
   * <code>string salt = 3;</code>
   * @return The bytes for salt.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSaltBytes() {
    java.lang.Object ref = salt_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      salt_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FIRSTNAME_FIELD_NUMBER = 4;
  private volatile java.lang.Object firstName_;
  /**
   * <code>string firstName = 4;</code>
   * @return The firstName.
   */
  @java.lang.Override
  public java.lang.String getFirstName() {
    java.lang.Object ref = firstName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      firstName_ = s;
      return s;
    }
  }
  /**
   * <code>string firstName = 4;</code>
   * @return The bytes for firstName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFirstNameBytes() {
    java.lang.Object ref = firstName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      firstName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LASTNAME_FIELD_NUMBER = 5;
  private volatile java.lang.Object lastName_;
  /**
   * <code>string lastName = 5;</code>
   * @return The lastName.
   */
  @java.lang.Override
  public java.lang.String getLastName() {
    java.lang.Object ref = lastName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      lastName_ = s;
      return s;
    }
  }
  /**
   * <code>string lastName = 5;</code>
   * @return The bytes for lastName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLastNameBytes() {
    java.lang.Object ref = lastName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      lastName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DATEOFBIRTH_FIELD_NUMBER = 6;
  private volatile java.lang.Object dateOfBirth_;
  /**
   * <code>string dateOfBirth = 6;</code>
   * @return The dateOfBirth.
   */
  @java.lang.Override
  public java.lang.String getDateOfBirth() {
    java.lang.Object ref = dateOfBirth_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      dateOfBirth_ = s;
      return s;
    }
  }
  /**
   * <code>string dateOfBirth = 6;</code>
   * @return The bytes for dateOfBirth.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDateOfBirthBytes() {
    java.lang.Object ref = dateOfBirth_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      dateOfBirth_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int GENDER_FIELD_NUMBER = 7;
  private int gender_;
  /**
   * <code>.com.gw.user.grpc.Gender gender = 7;</code>
   * @return The enum numeric value on the wire for gender.
   */
  @java.lang.Override public int getGenderValue() {
    return gender_;
  }
  /**
   * <code>.com.gw.user.grpc.Gender gender = 7;</code>
   * @return The gender.
   */
  @java.lang.Override public com.gw.user.grpc.Gender getGender() {
    @SuppressWarnings("deprecation")
    com.gw.user.grpc.Gender result = com.gw.user.grpc.Gender.valueOf(gender_);
    return result == null ? com.gw.user.grpc.Gender.UNRECOGNIZED : result;
  }

  public static final int HOMECOUNTRY_FIELD_NUMBER = 8;
  private volatile java.lang.Object homeCountry_;
  /**
   * <code>string homeCountry = 8;</code>
   * @return The homeCountry.
   */
  @java.lang.Override
  public java.lang.String getHomeCountry() {
    java.lang.Object ref = homeCountry_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      homeCountry_ = s;
      return s;
    }
  }
  /**
   * <code>string homeCountry = 8;</code>
   * @return The bytes for homeCountry.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getHomeCountryBytes() {
    java.lang.Object ref = homeCountry_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      homeCountry_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(userName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, userName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(password_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, password_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(salt_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, salt_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(firstName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, firstName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(lastName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, lastName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(dateOfBirth_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, dateOfBirth_);
    }
    if (gender_ != com.gw.user.grpc.Gender.GENDER_UNSPECIFIED.getNumber()) {
      output.writeEnum(7, gender_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(homeCountry_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, homeCountry_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(userName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, userName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(password_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, password_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(salt_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, salt_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(firstName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, firstName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(lastName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, lastName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(dateOfBirth_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, dateOfBirth_);
    }
    if (gender_ != com.gw.user.grpc.Gender.GENDER_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(7, gender_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(homeCountry_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, homeCountry_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.gw.user.grpc.UserCreateGrpcRequestDTO)) {
      return super.equals(obj);
    }
    com.gw.user.grpc.UserCreateGrpcRequestDTO other = (com.gw.user.grpc.UserCreateGrpcRequestDTO) obj;

    if (!getUserName()
        .equals(other.getUserName())) return false;
    if (!getPassword()
        .equals(other.getPassword())) return false;
    if (!getSalt()
        .equals(other.getSalt())) return false;
    if (!getFirstName()
        .equals(other.getFirstName())) return false;
    if (!getLastName()
        .equals(other.getLastName())) return false;
    if (!getDateOfBirth()
        .equals(other.getDateOfBirth())) return false;
    if (gender_ != other.gender_) return false;
    if (!getHomeCountry()
        .equals(other.getHomeCountry())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + USERNAME_FIELD_NUMBER;
    hash = (53 * hash) + getUserName().hashCode();
    hash = (37 * hash) + PASSWORD_FIELD_NUMBER;
    hash = (53 * hash) + getPassword().hashCode();
    hash = (37 * hash) + SALT_FIELD_NUMBER;
    hash = (53 * hash) + getSalt().hashCode();
    hash = (37 * hash) + FIRSTNAME_FIELD_NUMBER;
    hash = (53 * hash) + getFirstName().hashCode();
    hash = (37 * hash) + LASTNAME_FIELD_NUMBER;
    hash = (53 * hash) + getLastName().hashCode();
    hash = (37 * hash) + DATEOFBIRTH_FIELD_NUMBER;
    hash = (53 * hash) + getDateOfBirth().hashCode();
    hash = (37 * hash) + GENDER_FIELD_NUMBER;
    hash = (53 * hash) + gender_;
    hash = (37 * hash) + HOMECOUNTRY_FIELD_NUMBER;
    hash = (53 * hash) + getHomeCountry().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.gw.user.grpc.UserCreateGrpcRequestDTO parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gw.user.grpc.UserCreateGrpcRequestDTO parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gw.user.grpc.UserCreateGrpcRequestDTO parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gw.user.grpc.UserCreateGrpcRequestDTO parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gw.user.grpc.UserCreateGrpcRequestDTO parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gw.user.grpc.UserCreateGrpcRequestDTO parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gw.user.grpc.UserCreateGrpcRequestDTO parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.gw.user.grpc.UserCreateGrpcRequestDTO parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.gw.user.grpc.UserCreateGrpcRequestDTO parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.gw.user.grpc.UserCreateGrpcRequestDTO parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.gw.user.grpc.UserCreateGrpcRequestDTO parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.gw.user.grpc.UserCreateGrpcRequestDTO parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.gw.user.grpc.UserCreateGrpcRequestDTO prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.gw.user.grpc.UserCreateGrpcRequestDTO}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.gw.user.grpc.UserCreateGrpcRequestDTO)
      com.gw.user.grpc.UserCreateGrpcRequestDTOOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gw.user.grpc.UserManagementGrpc.internal_static_com_gw_user_grpc_UserCreateGrpcRequestDTO_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gw.user.grpc.UserManagementGrpc.internal_static_com_gw_user_grpc_UserCreateGrpcRequestDTO_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gw.user.grpc.UserCreateGrpcRequestDTO.class, com.gw.user.grpc.UserCreateGrpcRequestDTO.Builder.class);
    }

    // Construct using com.gw.user.grpc.UserCreateGrpcRequestDTO.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      userName_ = "";

      password_ = "";

      salt_ = "";

      firstName_ = "";

      lastName_ = "";

      dateOfBirth_ = "";

      gender_ = 0;

      homeCountry_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.gw.user.grpc.UserManagementGrpc.internal_static_com_gw_user_grpc_UserCreateGrpcRequestDTO_descriptor;
    }

    @java.lang.Override
    public com.gw.user.grpc.UserCreateGrpcRequestDTO getDefaultInstanceForType() {
      return com.gw.user.grpc.UserCreateGrpcRequestDTO.getDefaultInstance();
    }

    @java.lang.Override
    public com.gw.user.grpc.UserCreateGrpcRequestDTO build() {
      com.gw.user.grpc.UserCreateGrpcRequestDTO result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.gw.user.grpc.UserCreateGrpcRequestDTO buildPartial() {
      com.gw.user.grpc.UserCreateGrpcRequestDTO result = new com.gw.user.grpc.UserCreateGrpcRequestDTO(this);
      result.userName_ = userName_;
      result.password_ = password_;
      result.salt_ = salt_;
      result.firstName_ = firstName_;
      result.lastName_ = lastName_;
      result.dateOfBirth_ = dateOfBirth_;
      result.gender_ = gender_;
      result.homeCountry_ = homeCountry_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.gw.user.grpc.UserCreateGrpcRequestDTO) {
        return mergeFrom((com.gw.user.grpc.UserCreateGrpcRequestDTO)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.gw.user.grpc.UserCreateGrpcRequestDTO other) {
      if (other == com.gw.user.grpc.UserCreateGrpcRequestDTO.getDefaultInstance()) return this;
      if (!other.getUserName().isEmpty()) {
        userName_ = other.userName_;
        onChanged();
      }
      if (!other.getPassword().isEmpty()) {
        password_ = other.password_;
        onChanged();
      }
      if (!other.getSalt().isEmpty()) {
        salt_ = other.salt_;
        onChanged();
      }
      if (!other.getFirstName().isEmpty()) {
        firstName_ = other.firstName_;
        onChanged();
      }
      if (!other.getLastName().isEmpty()) {
        lastName_ = other.lastName_;
        onChanged();
      }
      if (!other.getDateOfBirth().isEmpty()) {
        dateOfBirth_ = other.dateOfBirth_;
        onChanged();
      }
      if (other.gender_ != 0) {
        setGenderValue(other.getGenderValue());
      }
      if (!other.getHomeCountry().isEmpty()) {
        homeCountry_ = other.homeCountry_;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              userName_ = input.readStringRequireUtf8();

              break;
            } // case 10
            case 18: {
              password_ = input.readStringRequireUtf8();

              break;
            } // case 18
            case 26: {
              salt_ = input.readStringRequireUtf8();

              break;
            } // case 26
            case 34: {
              firstName_ = input.readStringRequireUtf8();

              break;
            } // case 34
            case 42: {
              lastName_ = input.readStringRequireUtf8();

              break;
            } // case 42
            case 50: {
              dateOfBirth_ = input.readStringRequireUtf8();

              break;
            } // case 50
            case 56: {
              gender_ = input.readEnum();

              break;
            } // case 56
            case 66: {
              homeCountry_ = input.readStringRequireUtf8();

              break;
            } // case 66
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    private java.lang.Object userName_ = "";
    /**
     * <code>string userName = 1;</code>
     * @return The userName.
     */
    public java.lang.String getUserName() {
      java.lang.Object ref = userName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string userName = 1;</code>
     * @return The bytes for userName.
     */
    public com.google.protobuf.ByteString
        getUserNameBytes() {
      java.lang.Object ref = userName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string userName = 1;</code>
     * @param value The userName to set.
     * @return This builder for chaining.
     */
    public Builder setUserName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      userName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string userName = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearUserName() {
      
      userName_ = getDefaultInstance().getUserName();
      onChanged();
      return this;
    }
    /**
     * <code>string userName = 1;</code>
     * @param value The bytes for userName to set.
     * @return This builder for chaining.
     */
    public Builder setUserNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      userName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object password_ = "";
    /**
     * <code>string password = 2;</code>
     * @return The password.
     */
    public java.lang.String getPassword() {
      java.lang.Object ref = password_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        password_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string password = 2;</code>
     * @return The bytes for password.
     */
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string password = 2;</code>
     * @param value The password to set.
     * @return This builder for chaining.
     */
    public Builder setPassword(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      password_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string password = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPassword() {
      
      password_ = getDefaultInstance().getPassword();
      onChanged();
      return this;
    }
    /**
     * <code>string password = 2;</code>
     * @param value The bytes for password to set.
     * @return This builder for chaining.
     */
    public Builder setPasswordBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      password_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object salt_ = "";
    /**
     * <code>string salt = 3;</code>
     * @return The salt.
     */
    public java.lang.String getSalt() {
      java.lang.Object ref = salt_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        salt_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string salt = 3;</code>
     * @return The bytes for salt.
     */
    public com.google.protobuf.ByteString
        getSaltBytes() {
      java.lang.Object ref = salt_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        salt_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string salt = 3;</code>
     * @param value The salt to set.
     * @return This builder for chaining.
     */
    public Builder setSalt(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      salt_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string salt = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearSalt() {
      
      salt_ = getDefaultInstance().getSalt();
      onChanged();
      return this;
    }
    /**
     * <code>string salt = 3;</code>
     * @param value The bytes for salt to set.
     * @return This builder for chaining.
     */
    public Builder setSaltBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      salt_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object firstName_ = "";
    /**
     * <code>string firstName = 4;</code>
     * @return The firstName.
     */
    public java.lang.String getFirstName() {
      java.lang.Object ref = firstName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        firstName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string firstName = 4;</code>
     * @return The bytes for firstName.
     */
    public com.google.protobuf.ByteString
        getFirstNameBytes() {
      java.lang.Object ref = firstName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        firstName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string firstName = 4;</code>
     * @param value The firstName to set.
     * @return This builder for chaining.
     */
    public Builder setFirstName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      firstName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string firstName = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearFirstName() {
      
      firstName_ = getDefaultInstance().getFirstName();
      onChanged();
      return this;
    }
    /**
     * <code>string firstName = 4;</code>
     * @param value The bytes for firstName to set.
     * @return This builder for chaining.
     */
    public Builder setFirstNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      firstName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object lastName_ = "";
    /**
     * <code>string lastName = 5;</code>
     * @return The lastName.
     */
    public java.lang.String getLastName() {
      java.lang.Object ref = lastName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lastName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string lastName = 5;</code>
     * @return The bytes for lastName.
     */
    public com.google.protobuf.ByteString
        getLastNameBytes() {
      java.lang.Object ref = lastName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lastName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string lastName = 5;</code>
     * @param value The lastName to set.
     * @return This builder for chaining.
     */
    public Builder setLastName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      lastName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string lastName = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearLastName() {
      
      lastName_ = getDefaultInstance().getLastName();
      onChanged();
      return this;
    }
    /**
     * <code>string lastName = 5;</code>
     * @param value The bytes for lastName to set.
     * @return This builder for chaining.
     */
    public Builder setLastNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      lastName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object dateOfBirth_ = "";
    /**
     * <code>string dateOfBirth = 6;</code>
     * @return The dateOfBirth.
     */
    public java.lang.String getDateOfBirth() {
      java.lang.Object ref = dateOfBirth_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dateOfBirth_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string dateOfBirth = 6;</code>
     * @return The bytes for dateOfBirth.
     */
    public com.google.protobuf.ByteString
        getDateOfBirthBytes() {
      java.lang.Object ref = dateOfBirth_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dateOfBirth_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string dateOfBirth = 6;</code>
     * @param value The dateOfBirth to set.
     * @return This builder for chaining.
     */
    public Builder setDateOfBirth(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      dateOfBirth_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string dateOfBirth = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearDateOfBirth() {
      
      dateOfBirth_ = getDefaultInstance().getDateOfBirth();
      onChanged();
      return this;
    }
    /**
     * <code>string dateOfBirth = 6;</code>
     * @param value The bytes for dateOfBirth to set.
     * @return This builder for chaining.
     */
    public Builder setDateOfBirthBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      dateOfBirth_ = value;
      onChanged();
      return this;
    }

    private int gender_ = 0;
    /**
     * <code>.com.gw.user.grpc.Gender gender = 7;</code>
     * @return The enum numeric value on the wire for gender.
     */
    @java.lang.Override public int getGenderValue() {
      return gender_;
    }
    /**
     * <code>.com.gw.user.grpc.Gender gender = 7;</code>
     * @param value The enum numeric value on the wire for gender to set.
     * @return This builder for chaining.
     */
    public Builder setGenderValue(int value) {
      
      gender_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.com.gw.user.grpc.Gender gender = 7;</code>
     * @return The gender.
     */
    @java.lang.Override
    public com.gw.user.grpc.Gender getGender() {
      @SuppressWarnings("deprecation")
      com.gw.user.grpc.Gender result = com.gw.user.grpc.Gender.valueOf(gender_);
      return result == null ? com.gw.user.grpc.Gender.UNRECOGNIZED : result;
    }
    /**
     * <code>.com.gw.user.grpc.Gender gender = 7;</code>
     * @param value The gender to set.
     * @return This builder for chaining.
     */
    public Builder setGender(com.gw.user.grpc.Gender value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      gender_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.com.gw.user.grpc.Gender gender = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearGender() {
      
      gender_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object homeCountry_ = "";
    /**
     * <code>string homeCountry = 8;</code>
     * @return The homeCountry.
     */
    public java.lang.String getHomeCountry() {
      java.lang.Object ref = homeCountry_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        homeCountry_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string homeCountry = 8;</code>
     * @return The bytes for homeCountry.
     */
    public com.google.protobuf.ByteString
        getHomeCountryBytes() {
      java.lang.Object ref = homeCountry_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        homeCountry_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string homeCountry = 8;</code>
     * @param value The homeCountry to set.
     * @return This builder for chaining.
     */
    public Builder setHomeCountry(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      homeCountry_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string homeCountry = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearHomeCountry() {
      
      homeCountry_ = getDefaultInstance().getHomeCountry();
      onChanged();
      return this;
    }
    /**
     * <code>string homeCountry = 8;</code>
     * @param value The bytes for homeCountry to set.
     * @return This builder for chaining.
     */
    public Builder setHomeCountryBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      homeCountry_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.gw.user.grpc.UserCreateGrpcRequestDTO)
  }

  // @@protoc_insertion_point(class_scope:com.gw.user.grpc.UserCreateGrpcRequestDTO)
  private static final com.gw.user.grpc.UserCreateGrpcRequestDTO DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.gw.user.grpc.UserCreateGrpcRequestDTO();
  }

  public static com.gw.user.grpc.UserCreateGrpcRequestDTO getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UserCreateGrpcRequestDTO>
      PARSER = new com.google.protobuf.AbstractParser<UserCreateGrpcRequestDTO>() {
    @java.lang.Override
    public UserCreateGrpcRequestDTO parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<UserCreateGrpcRequestDTO> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UserCreateGrpcRequestDTO> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.gw.user.grpc.UserCreateGrpcRequestDTO getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

