// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: userservice.proto

package com.gw.user.grpc;

public interface UserCreateGrpcResponseDTOOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.gw.user.grpc.UserCreateGrpcResponseDTO)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool created = 1;</code>
   * @return The created.
   */
  boolean getCreated();
}
