// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserService.proto

package com.gw.user.grpc;

/**
 * Protobuf type {@code com.gw.user.grpc.UserCreateGrpcResponseDTO}
 */
public final class UserCreateGrpcResponseDTO extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.gw.user.grpc.UserCreateGrpcResponseDTO)
    UserCreateGrpcResponseDTOOrBuilder {
private static final long serialVersionUID = 0L;
  // Use UserCreateGrpcResponseDTO.newBuilder() to construct.
  private UserCreateGrpcResponseDTO(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UserCreateGrpcResponseDTO() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new UserCreateGrpcResponseDTO();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.gw.user.grpc.UserManagementGrpc.internal_static_com_gw_user_grpc_UserCreateGrpcResponseDTO_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.gw.user.grpc.UserManagementGrpc.internal_static_com_gw_user_grpc_UserCreateGrpcResponseDTO_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.gw.user.grpc.UserCreateGrpcResponseDTO.class, com.gw.user.grpc.UserCreateGrpcResponseDTO.Builder.class);
  }

  public static final int CREATED_FIELD_NUMBER = 1;
  private boolean created_;
  /**
   * <code>bool created = 1;</code>
   * @return The created.
   */
  @java.lang.Override
  public boolean getCreated() {
    return created_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (created_ != false) {
      output.writeBool(1, created_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (created_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, created_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.gw.user.grpc.UserCreateGrpcResponseDTO)) {
      return super.equals(obj);
    }
    com.gw.user.grpc.UserCreateGrpcResponseDTO other = (com.gw.user.grpc.UserCreateGrpcResponseDTO) obj;

    if (getCreated()
        != other.getCreated()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CREATED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getCreated());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.gw.user.grpc.UserCreateGrpcResponseDTO parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gw.user.grpc.UserCreateGrpcResponseDTO parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gw.user.grpc.UserCreateGrpcResponseDTO parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gw.user.grpc.UserCreateGrpcResponseDTO parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gw.user.grpc.UserCreateGrpcResponseDTO parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gw.user.grpc.UserCreateGrpcResponseDTO parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gw.user.grpc.UserCreateGrpcResponseDTO parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.gw.user.grpc.UserCreateGrpcResponseDTO parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.gw.user.grpc.UserCreateGrpcResponseDTO parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.gw.user.grpc.UserCreateGrpcResponseDTO parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.gw.user.grpc.UserCreateGrpcResponseDTO parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.gw.user.grpc.UserCreateGrpcResponseDTO parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.gw.user.grpc.UserCreateGrpcResponseDTO prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.gw.user.grpc.UserCreateGrpcResponseDTO}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.gw.user.grpc.UserCreateGrpcResponseDTO)
      com.gw.user.grpc.UserCreateGrpcResponseDTOOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gw.user.grpc.UserManagementGrpc.internal_static_com_gw_user_grpc_UserCreateGrpcResponseDTO_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gw.user.grpc.UserManagementGrpc.internal_static_com_gw_user_grpc_UserCreateGrpcResponseDTO_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gw.user.grpc.UserCreateGrpcResponseDTO.class, com.gw.user.grpc.UserCreateGrpcResponseDTO.Builder.class);
    }

    // Construct using com.gw.user.grpc.UserCreateGrpcResponseDTO.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      created_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.gw.user.grpc.UserManagementGrpc.internal_static_com_gw_user_grpc_UserCreateGrpcResponseDTO_descriptor;
    }

    @java.lang.Override
    public com.gw.user.grpc.UserCreateGrpcResponseDTO getDefaultInstanceForType() {
      return com.gw.user.grpc.UserCreateGrpcResponseDTO.getDefaultInstance();
    }

    @java.lang.Override
    public com.gw.user.grpc.UserCreateGrpcResponseDTO build() {
      com.gw.user.grpc.UserCreateGrpcResponseDTO result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.gw.user.grpc.UserCreateGrpcResponseDTO buildPartial() {
      com.gw.user.grpc.UserCreateGrpcResponseDTO result = new com.gw.user.grpc.UserCreateGrpcResponseDTO(this);
      result.created_ = created_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.gw.user.grpc.UserCreateGrpcResponseDTO) {
        return mergeFrom((com.gw.user.grpc.UserCreateGrpcResponseDTO)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.gw.user.grpc.UserCreateGrpcResponseDTO other) {
      if (other == com.gw.user.grpc.UserCreateGrpcResponseDTO.getDefaultInstance()) return this;
      if (other.getCreated() != false) {
        setCreated(other.getCreated());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              created_ = input.readBool();

              break;
            } // case 8
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    private boolean created_ ;
    /**
     * <code>bool created = 1;</code>
     * @return The created.
     */
    @java.lang.Override
    public boolean getCreated() {
      return created_;
    }
    /**
     * <code>bool created = 1;</code>
     * @param value The created to set.
     * @return This builder for chaining.
     */
    public Builder setCreated(boolean value) {
      
      created_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool created = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCreated() {
      
      created_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.gw.user.grpc.UserCreateGrpcResponseDTO)
  }

  // @@protoc_insertion_point(class_scope:com.gw.user.grpc.UserCreateGrpcResponseDTO)
  private static final com.gw.user.grpc.UserCreateGrpcResponseDTO DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.gw.user.grpc.UserCreateGrpcResponseDTO();
  }

  public static com.gw.user.grpc.UserCreateGrpcResponseDTO getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UserCreateGrpcResponseDTO>
      PARSER = new com.google.protobuf.AbstractParser<UserCreateGrpcResponseDTO>() {
    @java.lang.Override
    public UserCreateGrpcResponseDTO parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<UserCreateGrpcResponseDTO> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UserCreateGrpcResponseDTO> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.gw.user.grpc.UserCreateGrpcResponseDTO getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

