// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: userservice.proto

package com.gw.user.grpc;

public final class UserManagementGrpc {
  private UserManagementGrpc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gw_user_grpc_UserCreateGrpcRequestDTO_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_gw_user_grpc_UserCreateGrpcRequestDTO_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gw_user_grpc_UserCreateOrFindGrpcRequestDTO_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_gw_user_grpc_UserCreateOrFindGrpcRequestDTO_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gw_user_grpc_OauthUser_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_gw_user_grpc_OauthUser_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gw_user_grpc_UserCreateOrFindGrpcResponseDTO_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_gw_user_grpc_UserCreateOrFindGrpcResponseDTO_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gw_user_grpc_UserCreateGrpcResponseDTO_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_gw_user_grpc_UserCreateGrpcResponseDTO_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gw_user_grpc_UserAuthRequestDTO_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_gw_user_grpc_UserAuthRequestDTO_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gw_user_grpc_UserAuthDetailsDTO_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_gw_user_grpc_UserAuthDetailsDTO_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gw_user_grpc_UserAuthResponseDTO_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_gw_user_grpc_UserAuthResponseDTO_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gw_user_grpc_FetchUserDetailsByUserNameGrpcRequestDTO_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_gw_user_grpc_FetchUserDetailsByUserNameGrpcRequestDTO_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gw_user_grpc_UserDetailsGrpcResponseDTO_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_gw_user_grpc_UserDetailsGrpcResponseDTO_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021userservice.proto\022\020com.gw.user.grpc\032\033g" +
      "oogle/protobuf/empty.proto\032\013error.proto\"" +
      "c\n\030UserCreateGrpcRequestDTO\022\020\n\010userName\030" +
      "\001 \001(\t\022\020\n\010password\030\002 \001(\t\022\021\n\tfirstName\030\003 \001" +
      "(\t\022\020\n\010lastName\030\004 \001(\t\"g\n\036UserCreateOrFind" +
      "GrpcRequestDTO\022\020\n\010userName\030\001 \001(\t\0223\n\texts" +
      "ource\030\002 \001(\0162 .com.gw.user.grpc.ExternalS" +
      "ystem\"\035\n\tOauthUser\022\020\n\010userName\030\001 \001(\t\"\213\001\n" +
      "\037UserCreateOrFindGrpcResponseDTO\022+\n\004user" +
      "\030\001 \001(\0132\033.com.gw.user.grpc.OauthUserH\000\0221\n" +
      "\005error\030\002 \001(\0132 .com.gw.common.grpc.Genesi" +
      "sErrorH\000B\010\n\006either\",\n\031UserCreateGrpcResp" +
      "onseDTO\022\017\n\007created\030\001 \001(\010\"8\n\022UserAuthRequ" +
      "estDTO\022\020\n\010userName\030\001 \001(\t\022\020\n\010password\030\002 \001" +
      "(\t\"9\n\022UserAuthDetailsDTO\022\021\n\tfirstName\030\001 " +
      "\001(\t\022\020\n\010lastName\030\002 \001(\t\"\217\001\n\023UserAuthRespon" +
      "seDTO\022;\n\013authDetails\030\001 \001(\0132$.com.gw.user" +
      ".grpc.UserAuthDetailsDTOH\000\0221\n\005error\030\002 \001(" +
      "\0132 .com.gw.common.grpc.GenesisErrorH\000B\010\n" +
      "\006either\"<\n(FetchUserDetailsByUserNameGrp" +
      "cRequestDTO\022\020\n\010userName\030\001 \001(\t\"\177\n\032UserDet" +
      "ailsGrpcResponseDTO\022\020\n\010userName\030\001 \001(\t\022\020\n" +
      "\010password\030\002 \001(\t\022\021\n\tfirstName\030\003 \001(\t\022\020\n\010la" +
      "stName\030\004 \001(\t\022\014\n\004role\030\005 \001(\t\022\n\n\002id\030\006 \001(\t*7" +
      "\n\016ExternalSystem\022\013\n\007UNKNOWN\020\000\022\n\n\006GOOGLE\020" +
      "\001\022\014\n\010FACEBOOK\020\0022\315\003\n\013UserService\022\200\001\n\024fetc" +
      "hUsersByUserName\022:.com.gw.user.grpc.Fetc" +
      "hUserDetailsByUserNameGrpcRequestDTO\032,.c" +
      "om.gw.user.grpc.UserDetailsGrpcResponseD" +
      "TO\022[\n\014authenticate\022$.com.gw.user.grpc.Us" +
      "erAuthRequestDTO\032%.com.gw.user.grpc.User" +
      "AuthResponseDTO\022e\n\ncreateUser\022*.com.gw.u" +
      "ser.grpc.UserCreateGrpcRequestDTO\032+.com." +
      "gw.user.grpc.UserCreateGrpcResponseDTO\022w" +
      "\n\020createOrFindUser\0220.com.gw.user.grpc.Us" +
      "erCreateOrFindGrpcRequestDTO\0321.com.gw.us" +
      "er.grpc.UserCreateOrFindGrpcResponseDTOB" +
      "\026B\022UserManagementGrpcP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
          com.gw.common.grpc.ErrorGrpc.getDescriptor(),
        });
    internal_static_com_gw_user_grpc_UserCreateGrpcRequestDTO_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_gw_user_grpc_UserCreateGrpcRequestDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_gw_user_grpc_UserCreateGrpcRequestDTO_descriptor,
        new java.lang.String[] { "UserName", "Password", "FirstName", "LastName", });
    internal_static_com_gw_user_grpc_UserCreateOrFindGrpcRequestDTO_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_gw_user_grpc_UserCreateOrFindGrpcRequestDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_gw_user_grpc_UserCreateOrFindGrpcRequestDTO_descriptor,
        new java.lang.String[] { "UserName", "Extsource", });
    internal_static_com_gw_user_grpc_OauthUser_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_gw_user_grpc_OauthUser_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_gw_user_grpc_OauthUser_descriptor,
        new java.lang.String[] { "UserName", });
    internal_static_com_gw_user_grpc_UserCreateOrFindGrpcResponseDTO_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_gw_user_grpc_UserCreateOrFindGrpcResponseDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_gw_user_grpc_UserCreateOrFindGrpcResponseDTO_descriptor,
        new java.lang.String[] { "User", "Error", "Either", });
    internal_static_com_gw_user_grpc_UserCreateGrpcResponseDTO_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_gw_user_grpc_UserCreateGrpcResponseDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_gw_user_grpc_UserCreateGrpcResponseDTO_descriptor,
        new java.lang.String[] { "Created", });
    internal_static_com_gw_user_grpc_UserAuthRequestDTO_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_gw_user_grpc_UserAuthRequestDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_gw_user_grpc_UserAuthRequestDTO_descriptor,
        new java.lang.String[] { "UserName", "Password", });
    internal_static_com_gw_user_grpc_UserAuthDetailsDTO_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_com_gw_user_grpc_UserAuthDetailsDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_gw_user_grpc_UserAuthDetailsDTO_descriptor,
        new java.lang.String[] { "FirstName", "LastName", });
    internal_static_com_gw_user_grpc_UserAuthResponseDTO_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_com_gw_user_grpc_UserAuthResponseDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_gw_user_grpc_UserAuthResponseDTO_descriptor,
        new java.lang.String[] { "AuthDetails", "Error", "Either", });
    internal_static_com_gw_user_grpc_FetchUserDetailsByUserNameGrpcRequestDTO_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_com_gw_user_grpc_FetchUserDetailsByUserNameGrpcRequestDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_gw_user_grpc_FetchUserDetailsByUserNameGrpcRequestDTO_descriptor,
        new java.lang.String[] { "UserName", });
    internal_static_com_gw_user_grpc_UserDetailsGrpcResponseDTO_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_com_gw_user_grpc_UserDetailsGrpcResponseDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_gw_user_grpc_UserDetailsGrpcResponseDTO_descriptor,
        new java.lang.String[] { "UserName", "Password", "FirstName", "LastName", "Role", "Id", });
    com.google.protobuf.EmptyProto.getDescriptor();
    com.gw.common.grpc.ErrorGrpc.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
