// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: userservice.proto

package com.gw.user.grpc;

public interface UserAuthRequestDTOOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.gw.user.grpc.UserAuthRequestDTO)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string userName = 1;</code>
   * @return The userName.
   */
  java.lang.String getUserName();
  /**
   * <code>string userName = 1;</code>
   * @return The bytes for userName.
   */
  com.google.protobuf.ByteString
      getUserNameBytes();

  /**
   * <code>string password = 2;</code>
   * @return The password.
   */
  java.lang.String getPassword();
  /**
   * <code>string password = 2;</code>
   * @return The bytes for password.
   */
  com.google.protobuf.ByteString
      getPasswordBytes();
}
