// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: userservice.proto

package com.gw.user.grpc;

public final class UserManagementGrpc {
  private UserManagementGrpc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gw_user_grpc_UserCreateGrpcRequestDTO_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_gw_user_grpc_UserCreateGrpcRequestDTO_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gw_user_grpc_UserCreateGrpcResponseDTO_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_gw_user_grpc_UserCreateGrpcResponseDTO_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gw_user_grpc_UserAuthRequestDTO_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_gw_user_grpc_UserAuthRequestDTO_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gw_user_grpc_UserAuthResponseDTO_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_gw_user_grpc_UserAuthResponseDTO_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gw_user_grpc_FetchUserDetailsByUserNameGrpcRequestDTO_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_gw_user_grpc_FetchUserDetailsByUserNameGrpcRequestDTO_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gw_user_grpc_UserDetailsGrpcResponseDTO_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_gw_user_grpc_UserDetailsGrpcResponseDTO_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gw_user_grpc_ExternalUserCreateGrpcRequestDTO_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_gw_user_grpc_ExternalUserCreateGrpcRequestDTO_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gw_user_grpc_ExternalUserCreateGrpcResponseDTO_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_gw_user_grpc_ExternalUserCreateGrpcResponseDTO_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021userservice.proto\022\020com.gw.user.grpc\032\033g" +
      "oogle/protobuf/empty.proto\032\013error.proto\"" +
      "c\n\030UserCreateGrpcRequestDTO\022\020\n\010userName\030" +
      "\001 \001(\t\022\020\n\010password\030\002 \001(\t\022\021\n\tfirstName\030\003 \001" +
      "(\t\022\020\n\010lastName\030\004 \001(\t\",\n\031UserCreateGrpcRe" +
      "sponseDTO\022\017\n\007created\030\001 \001(\010\"8\n\022UserAuthRe" +
      "questDTO\022\020\n\010userName\030\001 \001(\t\022\020\n\010password\030\002" +
      " \001(\t\"f\n\023UserAuthResponseDTO\022\031\n\017isAuthent" +
      "icated\030\001 \001(\010H\000\022*\n\005error\030\002 \001(\0132\031.com.gw.c" +
      "ommon.grpc.ErrorH\000B\010\n\006either\"<\n(FetchUse" +
      "rDetailsByUserNameGrpcRequestDTO\022\020\n\010user" +
      "Name\030\001 \001(\t\"\177\n\032UserDetailsGrpcResponseDTO" +
      "\022\020\n\010userName\030\001 \001(\t\022\020\n\010password\030\002 \001(\t\022\021\n\t" +
      "firstName\030\003 \001(\t\022\020\n\010lastName\030\004 \001(\t\022\014\n\004rol" +
      "e\030\005 \001(\t\022\n\n\002id\030\006 \001(\t\"\256\001\n ExternalUserCrea" +
      "teGrpcRequestDTO\022\r\n\005email\030\001 \001(\t\022\021\n\tfirst" +
      "Name\030\002 \001(\t\022\020\n\010lastName\030\003 \001(\t\022\022\n\ntokenVal" +
      "ue\030\004 \001(\t\022\021\n\ttokenType\030\005 \001(\t\022\027\n\017tokenExpi" +
      "ryTime\030\006 \001(\003\022\026\n\016externalSystem\030\007 \001(\t\"#\n!" +
      "ExternalUserCreateGrpcResponseDTO2\323\003\n\013Us" +
      "erService\022\200\001\n\024fetchUsersByUserName\022:.com" +
      ".gw.user.grpc.FetchUserDetailsByUserName" +
      "GrpcRequestDTO\032,.com.gw.user.grpc.UserDe" +
      "tailsGrpcResponseDTO\022[\n\014authenticate\022$.c" +
      "om.gw.user.grpc.UserAuthRequestDTO\032%.com" +
      ".gw.user.grpc.UserAuthResponseDTO\022e\n\ncre" +
      "ateUser\022*.com.gw.user.grpc.UserCreateGrp" +
      "cRequestDTO\032+.com.gw.user.grpc.UserCreat" +
      "eGrpcResponseDTO\022}\n\022createExternalUser\0222" +
      ".com.gw.user.grpc.ExternalUserCreateGrpc" +
      "RequestDTO\0323.com.gw.user.grpc.ExternalUs" +
      "erCreateGrpcResponseDTOB\026B\022UserManagemen" +
      "tGrpcP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
          com.gw.common.grpc.ErrorGrpc.getDescriptor(),
        });
    internal_static_com_gw_user_grpc_UserCreateGrpcRequestDTO_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_gw_user_grpc_UserCreateGrpcRequestDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_gw_user_grpc_UserCreateGrpcRequestDTO_descriptor,
        new java.lang.String[] { "UserName", "Password", "FirstName", "LastName", });
    internal_static_com_gw_user_grpc_UserCreateGrpcResponseDTO_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_gw_user_grpc_UserCreateGrpcResponseDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_gw_user_grpc_UserCreateGrpcResponseDTO_descriptor,
        new java.lang.String[] { "Created", });
    internal_static_com_gw_user_grpc_UserAuthRequestDTO_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_gw_user_grpc_UserAuthRequestDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_gw_user_grpc_UserAuthRequestDTO_descriptor,
        new java.lang.String[] { "UserName", "Password", });
    internal_static_com_gw_user_grpc_UserAuthResponseDTO_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_gw_user_grpc_UserAuthResponseDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_gw_user_grpc_UserAuthResponseDTO_descriptor,
        new java.lang.String[] { "IsAuthenticated", "Error", "Either", });
    internal_static_com_gw_user_grpc_FetchUserDetailsByUserNameGrpcRequestDTO_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_gw_user_grpc_FetchUserDetailsByUserNameGrpcRequestDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_gw_user_grpc_FetchUserDetailsByUserNameGrpcRequestDTO_descriptor,
        new java.lang.String[] { "UserName", });
    internal_static_com_gw_user_grpc_UserDetailsGrpcResponseDTO_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_gw_user_grpc_UserDetailsGrpcResponseDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_gw_user_grpc_UserDetailsGrpcResponseDTO_descriptor,
        new java.lang.String[] { "UserName", "Password", "FirstName", "LastName", "Role", "Id", });
    internal_static_com_gw_user_grpc_ExternalUserCreateGrpcRequestDTO_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_com_gw_user_grpc_ExternalUserCreateGrpcRequestDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_gw_user_grpc_ExternalUserCreateGrpcRequestDTO_descriptor,
        new java.lang.String[] { "Email", "FirstName", "LastName", "TokenValue", "TokenType", "TokenExpiryTime", "ExternalSystem", });
    internal_static_com_gw_user_grpc_ExternalUserCreateGrpcResponseDTO_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_com_gw_user_grpc_ExternalUserCreateGrpcResponseDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_gw_user_grpc_ExternalUserCreateGrpcResponseDTO_descriptor,
        new java.lang.String[] { });
    com.google.protobuf.EmptyProto.getDescriptor();
    com.gw.common.grpc.ErrorGrpc.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
