// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: userservice.proto

package com.gw.user.grpc;

public interface UserAuthResponseDTOOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.gw.user.grpc.UserAuthResponseDTO)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool isAuthenticated = 1;</code>
   * @return Whether the isAuthenticated field is set.
   */
  boolean hasIsAuthenticated();
  /**
   * <code>bool isAuthenticated = 1;</code>
   * @return The isAuthenticated.
   */
  boolean getIsAuthenticated();

  /**
   * <code>.com.gw.common.grpc.Error error = 2;</code>
   * @return Whether the error field is set.
   */
  boolean hasError();
  /**
   * <code>.com.gw.common.grpc.Error error = 2;</code>
   * @return The error.
   */
  com.gw.common.grpc.Error getError();
  /**
   * <code>.com.gw.common.grpc.Error error = 2;</code>
   */
  com.gw.common.grpc.ErrorOrBuilder getErrorOrBuilder();

  public com.gw.user.grpc.UserAuthResponseDTO.EitherCase getEitherCase();
}
