apiVersion: v1
kind: Service
metadata:
  name: ping-app-deployment
  namespace: default
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: ping-app
  ports:
    - protocol: TCP
      port: 6060
      targetPort: 6060