// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.6
// source: user/proto/user_service.proto

package user

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// UserClient is the client API for User service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserClient interface {
	FetchUsersById(ctx context.Context, in *FetchUserDetailsByIdGrpcRequestDTO, opts ...grpc.CallOption) (*UserDetailsGrpcResponseDTO, error)
	FetchUsersByName(ctx context.Context, in *FetchUserDetailsByNameGrpcRequestDTO, opts ...grpc.CallOption) (*UserDetailsGrpcResponseDTO, error)
	AddUser(ctx context.Context, in *UserGrpcRequestDTO, opts ...grpc.CallOption) (*UserID, error)
	LoginWithPassword(ctx context.Context, in *LoginGrpcRequestDTO, opts ...grpc.CallOption) (*LoginGrpcResponseDTO, error)
}

type userClient struct {
	cc grpc.ClientConnInterface
}

func NewUserClient(cc grpc.ClientConnInterface) UserClient {
	return &userClient{cc}
}

func (c *userClient) FetchUsersById(ctx context.Context, in *FetchUserDetailsByIdGrpcRequestDTO, opts ...grpc.CallOption) (*UserDetailsGrpcResponseDTO, error) {
	out := new(UserDetailsGrpcResponseDTO)
	err := c.cc.Invoke(ctx, "/user.User/FetchUsersById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) FetchUsersByName(ctx context.Context, in *FetchUserDetailsByNameGrpcRequestDTO, opts ...grpc.CallOption) (*UserDetailsGrpcResponseDTO, error) {
	out := new(UserDetailsGrpcResponseDTO)
	err := c.cc.Invoke(ctx, "/user.User/FetchUsersByName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) AddUser(ctx context.Context, in *UserGrpcRequestDTO, opts ...grpc.CallOption) (*UserID, error) {
	out := new(UserID)
	err := c.cc.Invoke(ctx, "/user.User/AddUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) LoginWithPassword(ctx context.Context, in *LoginGrpcRequestDTO, opts ...grpc.CallOption) (*LoginGrpcResponseDTO, error) {
	out := new(LoginGrpcResponseDTO)
	err := c.cc.Invoke(ctx, "/user.User/LoginWithPassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServer is the server API for User service.
// All implementations must embed UnimplementedUserServer
// for forward compatibility
type UserServer interface {
	FetchUsersById(context.Context, *FetchUserDetailsByIdGrpcRequestDTO) (*UserDetailsGrpcResponseDTO, error)
	FetchUsersByName(context.Context, *FetchUserDetailsByNameGrpcRequestDTO) (*UserDetailsGrpcResponseDTO, error)
	AddUser(context.Context, *UserGrpcRequestDTO) (*UserID, error)
	LoginWithPassword(context.Context, *LoginGrpcRequestDTO) (*LoginGrpcResponseDTO, error)
	mustEmbedUnimplementedUserServer()
}

// UnimplementedUserServer must be embedded to have forward compatible implementations.
type UnimplementedUserServer struct {
}

func (UnimplementedUserServer) FetchUsersById(context.Context, *FetchUserDetailsByIdGrpcRequestDTO) (*UserDetailsGrpcResponseDTO, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchUsersById not implemented")
}
func (UnimplementedUserServer) FetchUsersByName(context.Context, *FetchUserDetailsByNameGrpcRequestDTO) (*UserDetailsGrpcResponseDTO, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchUsersByName not implemented")
}
func (UnimplementedUserServer) AddUser(context.Context, *UserGrpcRequestDTO) (*UserID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddUser not implemented")
}
func (UnimplementedUserServer) LoginWithPassword(context.Context, *LoginGrpcRequestDTO) (*LoginGrpcResponseDTO, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginWithPassword not implemented")
}
func (UnimplementedUserServer) mustEmbedUnimplementedUserServer() {}

// UnsafeUserServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserServer will
// result in compilation errors.
type UnsafeUserServer interface {
	mustEmbedUnimplementedUserServer()
}

func RegisterUserServer(s grpc.ServiceRegistrar, srv UserServer) {
	s.RegisterService(&User_ServiceDesc, srv)
}

func _User_FetchUsersById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchUserDetailsByIdGrpcRequestDTO)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).FetchUsersById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.User/FetchUsersById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).FetchUsersById(ctx, req.(*FetchUserDetailsByIdGrpcRequestDTO))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_FetchUsersByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchUserDetailsByNameGrpcRequestDTO)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).FetchUsersByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.User/FetchUsersByName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).FetchUsersByName(ctx, req.(*FetchUserDetailsByNameGrpcRequestDTO))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_AddUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserGrpcRequestDTO)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).AddUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.User/AddUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).AddUser(ctx, req.(*UserGrpcRequestDTO))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_LoginWithPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginGrpcRequestDTO)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).LoginWithPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.User/LoginWithPassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).LoginWithPassword(ctx, req.(*LoginGrpcRequestDTO))
	}
	return interceptor(ctx, in, info, handler)
}

// User_ServiceDesc is the grpc.ServiceDesc for User service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var User_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.User",
	HandlerType: (*UserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FetchUsersById",
			Handler:    _User_FetchUsersById_Handler,
		},
		{
			MethodName: "FetchUsersByName",
			Handler:    _User_FetchUsersByName_Handler,
		},
		{
			MethodName: "AddUser",
			Handler:    _User_AddUser_Handler,
		},
		{
			MethodName: "LoginWithPassword",
			Handler:    _User_LoginWithPassword_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user/proto/user_service.proto",
}
