name: Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  FunctionalTest:
    uses: ./.github/workflows/functionalTest.yml
    secrets:
      OAUTH_CLIENT_ID_GOOGLE: ${{ secrets.OAUTH_CLIENT_ID_GOOGLE }}
      OAUTH_CLIENT_SECRET_GOOGLE: ${{ secrets.OAUTH_CLIENT_SECRET_GOOGLE }}

  Sonar:
    uses: ./.github/workflows/sonar.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_CLOUD_TOKEN }}

  tag_release:
    if: github.ref == 'refs/heads/master' && contains(github.event.head_commit.message, '#release')
    needs: [ FunctionalTest, Sonar ]
    permissions:
      id-token: write # need this for OIDC
      contents: read
    uses: ./.github/workflows/create_release_tag.yml
    secrets:
      AWS-ROLE: ${{ secrets.GHA_AWS_ROLE }}
      ALL_ACCESS_TOKEN: ${{ secrets.ALL_ACCESS_TOKEN }}

#  publish_test_image:
#    needs: [ tag_release ]
#    uses: ./.github/workflows/publish_test_images.yml
#    secrets:
#      AWS-ROLE: ${{ secrets.GHA_AWS_ROLE }}
#      ALL_ACCESS_TOKEN: ${{ secrets.ALL_ACCESS_TOKEN }}
#      ECR-TEST-REPO: ${{ secrets.ECR_TEST_REPO }}