name: Publish latest images

on:
  workflow_dispatch:

jobs:
  get_latest_tag:
    runs-on: ubuntu-latest
    outputs:
      release_tag: ${{ steps.fetch_tag.outputs.LATEST_TAG }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Get latest tag
        id: fetch_tag
        shell: bash
        run: |
          LATEST_TAG=`git describe --tags $(git rev-list --tags --max-count=1)`
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_OUTPUT

  build-and-push-image:
    name: Build image for microservices
    runs-on: ubuntu-latest
    needs: [ release, validate-microservices ]
    if: "needs.validate-microservices.outputs.microservices != ''"
    strategy:
      matrix:
        microservice: ${{ fromJson(needs.validate-microservices.outputs.microservices) }}
        region:
          - eu-west-1
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Install Protoc on the box
        run: sudo apt install -y protobuf-compiler

      - name: Build without the test
        run: |
          echo "Microservice: ${{ matrix.region }}" >> $GITHUB_STEP_SUMMARY
          ./mvnw clean package -DskipTests=true

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ matrix.region }}
          role-to-assume: ${{ secrets.GHA_AWS_ROLE }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Image for service
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ needs.get_latest_tag.outputs.release_tag }}
        run: |
          echo "Building image for service: ${{ matrix.microservice }}" >> $GITHUB_STEP_SUMMARY
          echo "Current Working Directory: `pwd`" >> $GITHUB_STEP_SUMMARY
          cd ${{ matrix.microservice }}
          docker build -t ${{ matrix.microservice }}:$IMAGE_TAG .
          docker tag ${{ matrix.microservice }}:$IMAGE_TAG ${{ secrets.ECR-TEST-REPO }}/${{ matrix.microservice }}:$IMAGE_TAG
          echo "Pushing image push ${{ secrets.ECR-TEST-REPO }}/${{ matrix.microservice }}:$IMAGE_TAG to ECR..." >> $GITHUB_STEP_SUMMARY
          docker push ${{ secrets.ECR-TEST-REPO }}/${{ matrix.microservice }}:$IMAGE_TAG